const m = 1

try {
  const m = 2
} catch (error) {
}

console.log('end')